# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- tagcloud
- recent_posts
- category
# - tag
- archive
- links

plugins:
- hexo-generator-feed

# Links
links:
  liecol's 主页: http://www.bloggao.cn
  liecol's 商城: http://shop.bloggao.cn
  liecol's 招聘: http://zpw.bloggao.cn
  liecol's 快递: http://ltkd.bloggao.cn
  菜鸟-Miao: http://blog.newbmiao.com

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: liecol

# Baidu share
baidushare: true